/** Stable Decree finding codes — do not rename without a migration note. */
export const CODES = Object.freeze({
  NATIVE_ELEMENT: 'DECREE_NATIVE_ELEMENT',
  HARDCODED_HEX: 'DECREE_HARDCODED_HEX',
  HARDCODED_COLOR: 'DECREE_HARDCODED_COLOR',
  ARBITRARY_VALUE: 'DECREE_ARBITRARY_VALUE',
  UNKNOWN_COMPONENT: 'DECREE_UNKNOWN_COMPONENT',
  UNKNOWN_TOKEN: 'DECREE_UNKNOWN_TOKEN',
  DEPRECATED_COMPONENT: 'DECREE_DEPRECATED_COMPONENT',
  DEPRECATED_TOKEN: 'DECREE_DEPRECATED_TOKEN',
  INVALID_CONTRACT: 'DECREE_INVALID_CONTRACT',
  SNIPPET_TOO_LARGE: 'DECREE_SNIPPET_TOO_LARGE',
});
